version: "3"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    logging:
      options:
        max-size: 10m
        max-file: "3"

  keycloak:
    image: jboss/keycloak
    ports:
    - 8081:8080
    depends_on:
      - postgres
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak

