server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:password@localhost:27017/saturn-db?authSource=admin&authMechanism=SCRAM-SHA-1}

management:
  endpoints:
    web:
      exposure:
        include: "*"

ping-pong:
  pingServerUrl: ${PING_PONG_SERVER_URL:http://localhost:8180/hystrix}

#springfox:
#  documentation:
#    swagger-ui:
#      base-url: /swagger

keycloak:
  enabled: ${KEYCLOAK_ENABLED:false}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  public-client: ${KEYCLOAK_PUBLIC_CLIENT}

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: false
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql