server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "*"

ping-pong:
  pingServerUrl: ${PING_PONG_SERVER_URL:http://localhost:8180/hystrix}

#springfox:
#  documentation:
#    swagger-ui:
#      base-url: /swagger

keycloak:
  enabled: ${KEYCLOAK_ENABLED:false}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  public-client: ${KEYCLOAK_PUBLIC_CLIENT}
