graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: false
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true

graphiql:
  enabled: true
  mapping: /graphiql
  endpoint:
    graphql: /graphql